// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Temporary hardcoded values until .env file is properly formatted
const SUPABASE_URL = "https://hnihvpuoopnaprofufrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuaWh2cHVvb3BuYXByb2Z1ZnJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMjQyOTIsImV4cCI6MjA3MDkwMDI5Mn0.dAstVdN-yrn152UEqDvCo04gQI6BO0_mr8TpUA-oDYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});